[workspace]
members = [
    "blocks",
    "glw",
    "sdf_tool",
]

[profile.dev]
opt-level = 3
lto = "thin"
# codegen-units = 1
incremental = false

[profile.test]
opt-level = 3
lto = "thin"
# codegen-units = 1
incremental = false