[package]
authors = ["Mick van Gelderen <mickvangelderen@gmail.com>"]
name = "blocks"
version = "0.1.0"

[dependencies]
cgmath = "0.16.1"
gl = "0.10.0"
glutin = "0.18.0"
image = "0.19.0"
notify = "4.0.3"

[dependencies.glw]
path = "../glw"
features = ["prevent_drop_panic"]
